version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    networks:
      - my-network

  mariadb:
    image: mariadb-image:seoson
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db-volume:/var/lib/mysql
    privileged: true
    healthcheck:
      interval: 5s
      test:
        [
          "CMD-SHELL",
          "mariadb-admin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1",
        ]
      timeout: 10s
      retries: 3
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure
    networks:
      - my-network
    init: true

networks:
  my-network:
volumes:
  db-volume: